# Generated by Django 3.1.6 on 2021-06-05 17:41

from django.db import migrations, models
import financial_server.core.utils
import thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('logo', thumbnails.fields.ImageField(blank=True, null=True, upload_to=financial_server.core.utils.FilenameGenerator(prefix='category_logos'))),
            ],
        ),
    ]
