# Generated by Django 3.1.6 on 2021-02-07 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import financial_server.apps.users.models
import financial_server.core.utils
import financial_server.core.validators
import thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissions', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('nik', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.PositiveSmallIntegerField(blank=True, choices=[(11, 'Aceh'), (12, 'Sumatera Utara'), (13, 'Sumatera Barat'), (14, 'Riau'), (15, 'Jambi'), (16, 'Sumatera Selatan'), (17, 'Bengkulu'), (18, 'Lampung'), (19, 'Kepulauan Bangka Belitung'), (21, 'Kepulauan Riau'), (31, 'DKI Jakarta'), (32, 'Jawa Barat'), (33, 'Jawa Tengah'), (34, 'DI Yogyakarta'), (35, 'Jawa Timur'), (36, 'Banten'), (51, 'Bali'), (52, 'Nusa Tenggara Barat'), (52, 'Nusa Tenggara Timur'), (61, 'Kalimantan Barat'), (62, 'Kalimantan Tengah'), (63, 'Kalimantan Selatan'), (64, 'Kalimantan Timur'), (65, 'Kalimantan Utara'), (71, 'Sulawesi Utara'), (72, 'Sulawesi Tengah'), (73, 'Sulawesi Selatan'), (74, 'Sulawesi Tenggara'), (75, 'Gorontalo'), (76, 'Sulawesi Barat'), (81, 'Maluku'), (82, 'Maluku Utara'), (91, 'Papua'), (92, 'Papua Barat')], null=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Whether the user can log into backoffice.', verbose_name='Can access backoffice')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('has_incorrect_email', models.BooleanField(default=False)),
                ('phone', models.CharField(db_index=True, max_length=30, validators=[financial_server.core.validators.validate_mobile_phone], verbose_name='Mobile Number')),
                ('is_verified', models.BooleanField(default=False)),
                ('backoffice_permissions', models.ManyToManyField(blank=True, to='permissions.Permission')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', financial_server.apps.users.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', thumbnails.fields.ImageField(blank=True, null=True, upload_to=financial_server.core.utils.FilenameGenerator(prefix='profiles'))),
                ('id_card_photo', thumbnails.fields.ImageField(blank=True, null=True, upload_to=financial_server.core.utils.FilenameGenerator(prefix='id_cards'))),
                ('id_card_address', models.TextField(blank=True, default='')),
                ('address', models.TextField(default='')),
                ('postal_code', models.TextField(blank=True, default='', max_length=5)),
                ('birthday', models.DateField()),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Laki-Laki'), (2, 'Perempuan')])),
                ('religion', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Islam'), (2, 'Katolik'), (3, 'Protestan'), (4, 'Hindu'), (5, 'Budha'), (6, 'Konghucu'), (7, 'Lain-lain')], null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
