# Generated by Django 3.1.6 on 2021-02-07 02:52

from django.db import migrations

from financial_server.apps.permissions.constants import PermissionType


def populate_permissions(apps, schema_editor):
    Permission = apps.get_model("permissions", "Permission")
    PermissionGroup = apps.get_model("permissions", "PermissionGroup")

    user_group, _ = PermissionGroup.objects.get_or_create(name='User')

    Permission.objects.get_or_create(name=PermissionType.VIEW_USER.value, group=user_group)
    Permission.objects.get_or_create(name=PermissionType.VERIFY_USER.value, group=user_group)
    Permission.objects.get_or_create(name=PermissionType.ADD_USER.value, group=user_group)
    Permission.objects.get_or_create(name=PermissionType.EDIT_USER.value, group=user_group)


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_permissions, migrations.RunPython.noop),
    ]
