# Generated by Django 3.1.6 on 2021-02-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
