# Generated by Django 3.2.6 on 2021-09-11 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0002_auto_20210213_2035'),
        ('transactions', '0004_transaction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='balances.balance'),
        ),
    ]
