# Generated by Django 3.1.6 on 2021-06-05 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('goal_name', models.CharField(blank=True, max_length=64, null=True)),
                ('achievement_date', models.DateField(blank=True, db_index=True, null=True)),
                ('deposit_cycle', models.PositiveSmallIntegerField(choices=[(1, 'Harian'), (2, 'Mingguan'), (3, 'Bulanan'), (4, 'Tahunan')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
