# Generated by Django 3.1.6 on 2021-06-05 18:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financial_goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialgoal',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.CreateModel(
            name='GoalSavingsTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financial_goals.financialgoal')),
            ],
        ),
    ]
