name: CodeCov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: checkout@v1
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m manage.py test --parallel --exclude-tag=sms_office_test
