name: Example workflow for Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Restore pip cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Use local settings
      run: cp financial_server/local_settings.py.ci financial_server/local_settings.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
    - name: Running Unittest
      run: |
        coverage run --source='.' manage.py test --parallel && coverage report --fail-under=75 && coverage xml
    - name: Report coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        token: '66f7af80-699e-4429-baef-e55e21f73359'
        files: ./coverage.xml
        directory: ./coverage/reports/
        fail_ci_if_error: true
