name: CodeCov
on: [push]
jobs:
  runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Restore pip cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Use local settings
      run: cp dana_bagus_server/local_settings.py.ci dana_bagus_server/local_settings.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate Report
      run: |
        coverage run -m manage.py --parallel --exclude-tag=sms_office_test
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
      with:

    
