name: Example workflow for Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Generate coverage report
      run: |
        pip install pytest
        export DIFF_FILES=$(git diff --name-only --diff-filter=ACM $(git merge-base HEAD origin/master) | grep "\.py" | grep -v "settings" | grep -v "migrations")
        if [[ ! -z $DIFF_FILES ]]
        then
          echo "[Eslint] Checking ..." $DIFF_FILES
          coverage run --source='.' manage.py test --parallel
          coverage report
        fi
